-- Products Table
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price INT NOT NULL,
    category TEXT NOT NULL,
    cost_per_item INT DEFAULT 0
);
-- 初期商品の登録
INSERT INTO products (name, price, category, cost_per_item) VALUES 
('麦茶', 100, 'ドリンク', 40), 
('ストロベリースムージー', 400, 'ドリンク', 200),
('スナックセット', 300, 'お菓子', 150);

-- Orders Table
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_amount INT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    is_lucky BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Order Items Table
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    quantity INT NOT NULL,
    price INT NOT NULL
);

-- Users, Expenses, Shifts, etc.
CREATE TABLE users ( id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL, pin TEXT NOT NULL );
CREATE TABLE expenses ( id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, item TEXT NOT NULL, amount INT NOT NULL, created_at TIMESTAMPTZ DEFAULT now() );
CREATE TABLE shifts ( id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL );
CREATE TABLE shift_assignments ( id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE, shift_id BIGINT REFERENCES shifts(id) ON DELETE CASCADE, shift_date DATE NOT NULL );
